version: '3.7'

services:
  # PostgreSQL database
  postgres:
    image: postgres:13
    container_name: postgres_container
    environment:
      POSTGRES_DB: billMunshi
      POSTGRES_USER: bill
      POSTGRES_PASSWORD: Bill@1234
    build:
      context: .
      dockerfile: Dockerfile.postgres  # Specify a Dockerfile for PostgreSQL if needed
