# Generated by Django 4.2.8 on 2023-12-17 04:44

import bills.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillAnalyzer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('billName', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='bills/', validators=[bills.models.validate_file_extension])),
                ('formData', models.JSONField(blank=True, default=dict, null=True)),
                ('tableData', models.JSONField(blank=True, default=dict, null=True)),
                ('status', models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Analysed', 'Analysed'), ('Synced', 'Synced')], default='Draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Bill',
            },
        ),
        migrations.CreateModel(
            name='ZohoBill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('bill_no', models.CharField(blank=True, max_length=50, null=True)),
                ('bill_date', models.CharField(blank=True, max_length=50, null=True)),
                ('total', models.CharField(blank=True, default=0, max_length=50, null=True)),
                ('igst', models.CharField(blank=True, default=0, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('selectBill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bills.billanalyzer')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.zohovendor')),
            ],
            options={
                'verbose_name_plural': 'Zoho Bill Analysis Report',
            },
        ),
        migrations.CreateModel(
            name='ZohoProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('item_name', models.CharField(blank=True, max_length=100, null=True)),
                ('item_details', models.CharField(blank=True, max_length=200, null=True)),
                ('rate', models.CharField(blank=True, max_length=10, null=True)),
                ('quantity', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('amount', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chart_of_accounts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.zohochartofaccount')),
                ('taxes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.zohotaxes')),
                ('zohoBill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='bills.zohobill')),
            ],
            options={
                'verbose_name_plural': 'Zoho Bill Product Analysis Report',
            },
        ),
    ]
