# Generated by Django 4.2.8 on 2023-12-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billanalyzer',
            name='bill_id',
            field=models.IntegerField(auto_created=True, default=0, editable=False, unique=True),
        ),
    ]
