# Generated by Django 4.2.8 on 2023-12-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_remove_billanalyzer_bill_id_billanalyzer_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billanalyzer',
            name='unique_id',
            field=models.CharField(max_length=200),
        ),
    ]
