# Generated by Django 4.2.8 on 2023-12-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_alter_billanalyzer_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='zohobill',
            name='note',
            field=models.CharField(blank=True, default='Enter Your Description', max_length=100, null=True),
        ),
    ]
