# Generated by Django 4.2.8 on 2023-12-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0005_zohobill_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billanalyzer',
            name='unique_id',
        ),
        migrations.AlterField(
            model_name='billanalyzer',
            name='billName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
