# Generated by Django 4.2.8 on 2023-12-16 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZohoVendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('contactId', models.CharField(max_length=100, unique=True)),
                ('companyName', models.CharField(max_length=100)),
                ('gstNo', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Zoho Vendor',
            },
        ),
        migrations.CreateModel(
            name='ZohoTaxes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('taxId', models.CharField(max_length=100)),
                ('taxName', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Zoho Taxes',
            },
        ),
        migrations.CreateModel(
            name='ZohoCredentials',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('clientId', models.CharField(max_length=100)),
                ('clientSecret', models.CharField(max_length=100)),
                ('accessCode', models.CharField(default='Your Access Code', max_length=200)),
                ('organisationId', models.CharField(default='Your organisationId', max_length=100)),
                ('redirectUrl', models.CharField(default='Your Redirect URL', max_length=200)),
                ('accessToken', models.CharField(blank=True, max_length=200, null=True)),
                ('refreshToken', models.CharField(blank=True, max_length=200, null=True)),
                ('bearerToken', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Zoho Credentials',
            },
        ),
        migrations.CreateModel(
            name='ZohoChartOfAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('accountId', models.CharField(max_length=100)),
                ('accountName', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Zoho Chart Of Accounts',
            },
        ),
    ]
